### PR TITLE
Change tracks file for repository rename

### PR DESCRIPTION
**Pull request by jackieokay**
@dirk-thomas @tfoote based on our discussion about the urdfdom/urdf_parser_py repo migration, does this look correct to you?

### CODE REVIEW

**Comment by tfoote** [comment]
Is this not becoming a ROS package and as such the package.xml should go upstream?

**Comment by jackieokay** [comment]
Yeah, it would probably simplify things if the package.xml was upstream.

In my understanding, this package has always been released as a ROS package and is not a system package, but previously lived within the urdfdom repo, with a package that gets released as a system package.

Some users such as @traversaro don't install this as a catkin package, but instead use the setup.py approach (because they use it on Windows). But keeping the package.xml file upstream probably wouldn't hurt them.

**Comment by jackieokay** [comment]
If I remove the package.xmls in this pull request and add a package.xml in indigo-devel branch of the source repository (which has actually already been done), it should just work, right?

**Comment by tfoote** [comment]
Yes, though looking into the repo it looks like there are also overlayed CMakeLists and setup.py files as well as the package.xml. 

Moving those versions files trunk will require catkin_pkg but that's also pure python package and I believe it would be fine to continue using the pure setup.py approach, just with catkin_pkg installed. Then there would not be different behavior depending on from where you installed.

**Comment by dirk-thomas** [comment]
This repo should then be renamed to `urdf_parser_py-release`.

**Comment by jackieokay** [comment]
The package is still called urdfdom-py. I was considering renaming the package because the repository is called `urdf_parser_py` and the python package is called `urdf_parser_py`, but I was worried that this would disrupt the install configurations of users.

**Comment by dirk-thomas** [comment]
I was mislead by the project name in the CMake file: https://github.com/ros/urdf_parser_py/blob/3a83bbc0c3077fedb079e8765d61cd90c4e60c69/CMakeLists.txt#L2

Keeping it sounds good then.

**Comment by jackieokay** [comment]
@tfoote But since there are users who want to use a pure setup.py approach who can't install `catkin_pkg`, like the Windows case I mentioned in my previous post, won't adding `catkin_pkg` make the setup.py unusable for them?

**Comment by tfoote** [comment]
catkin_pkg is pure python it just load the metadata from the package.xml instead of it being written directly into the setup.py file.

**Comment by jackieokay** [comment]
Awesome. I will update the CMakeLists and setup.py in the upstream repo and remove them in this PR.

**Comment by jackieokay** [comment]
ros/urdf_parser_py#2 moves the CMakeLists and setup.py to the upstream repo.

**Comment by jackieokay** [comment]
Going to merge this and try releasing the package.

**Pull request merged**
